version: '3'
services:
  cypress:
    image: "cypress/included:cypress-12.17.2-node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1"
    #command: ["--browser", "chrome"]
    working_dir: /e2e
    volumes:
      - ./cypress:/e2e
      - ./cypress/reports:/e2e/cypress/reports  # Montar la carpeta de informes como un volumen
    command: ["./node_modules/.bin/cypress", "run"]
    user: "${UID}:${GID}"  # <-- Agrega esta línea para ejecutar el contenedor como usuario actual